---
name: codeworld-tasks
version: 0.1.0.0
github: "fmidue/codeworld-tasks"
license: BSD-3-Clause
author: "Patrick Ritzenfeld"
maintainer: "patrick.ritzenfeld@uni-due.de"
copyright: "2024 Patrick Ritzenfeld"

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/fmidue/codeworld-tasks#readme>

dependencies:
  - base >= 4.11 && < 5
  - bytestring
  - bytestring-trie
  - containers
  - data-reify
  - deepseq
  - extra
  - mtl
  - text

ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - CodeWorld.Tasks
    - CodeWorld.Tasks.Types
    - CodeWorld.Tasks.API
    - CodeWorld.Tasks.Normalize
    - CodeWorld.Tasks.VectorSpace
    - CodeWorld.Tasks.Compare
    - CodeWorld.Tasks.HashCons
    - CodeWorld.Tasks.Reify
    - CodeWorld.Tasks.Trie
    - CodeWorld.Tasks.Solution
    - CodeWorld.Tasks.Relative
    - CodeWorld.Tasks.Examples

tests:
  codeworld-tasks-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - codeworld-tasks
