---
name: observable-sharing
version: 0.1.0.0
github: "patritzenfeld/observable-sharing"
license: BSD-3-Clause
author: "Patrick Ritzenfeld"
maintainer: "patrick.ritzenfeld@uni-due.de"
copyright: "2024 Patrick Ritzenfeld"

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/patritzenfeld/observable-sharing#readme>

dependencies:
  - base >= 4.11 && < 5
  - bytestring
  - bytestring-trie
  - data-reify
  - containers
  - mtl
  - text

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

tests:
  observable-sharing-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - observable-sharing
